### ISSUE TITLE
Upgrade to postgresql 14

### ISSUE THREAD

**Issue by lmsurpre** [Alvearie/alvearie-helm#66]
Postgresql 14 contains many updates and, since this helm chart is relatively immature (pre-1.0), it might be nice to make that our default before going 1.0. 

One change in v14 in particular seems like it could benefit us:
* VACUUM automatically becomes more aggressive, and skips inessential cleanup, if the database starts to approach a transaction ID wraparound condition.

The support for OUT parameters from stored procs could also be useful to normalize our approach across dbs (but not until we can drop support for older postgres versions).

The problem with this change is that anyone that is using our existing embedded postgresql chart with the default postgresql version could be broken by this.  On a test cluster I tried a naive update and it resulted in this:
```
postgresql 14:27:55.94 INFO  ==> ** Starting PostgreSQL **
2021-11-22 14:27:55.954 GMT [1] FATAL:  database files are incompatible with server
2021-11-22 14:27:55.954 GMT [1] DETAIL:  The data directory was initialized by PostgreSQL version 13, which is not compatible with this version 14.1.
```

The bitnami helm chart doesn't offer much in the way of migration help...just this blurb from the README:
> In this case, you should migrate the data from the old chart to the new one following an approach similar to that described in [this section](https://www.postgresql.org/docs/current/upgrading.html#UPGRADING-VIA-PGDUMPALL) from the official documentation. Basically, create a database dump in the old chart, move and restore it in the new one.

To me, its just more reason to upgrade to v14 *before* we call our chart 1.0 (since it might be painful for users to make that upgrade later), but we'll probably want to include some notes in the README for anyone using the current default version.

**Comment by lmsurpre** [comment]
@michaelwschroeder @chgl @punktilious any thoughts?

**Comment by chgl** [comment]
I'm in favor. I personally don't think using the included postgres chart is the best idea for a production deployment anyway, where a postgres operator or the cloud provider of choice's offering may be more appropriate (automatic failover, connection pooling, backups, etc.). But it's great for smaller scale, CI, testing, and development.

People using and depending on a previous postgres version can still override and downgrade the `postgresql.image.tag` since the update will just complain about incompatibility but not corrupt any data.

**Comment by lmsurpre** [comment]
done in https://github.com/Alvearie/alvearie-helm/pull/70 for 0.6.0
